CREATE DATABASE SERVICIOSDB

CREATE TABLE SERVICIOS (
  ID SERIAL,
  CENTRO_COMERCIAL VARCHAR(255) NOT NULL,
  OPERADOR VARCHAR(255) NOT NULL,
  NRO_CONTRATO VARCHAR(255) NOT NULL,
  SUCURSAL VARCHAR(255) NOT NULL,
  OPM_MEDIDOR VARCHAR(255) NOT NULL,
  TARIFA VARCHAR(255) NOT NULL,
  TIPO_MEDIDOR VARCHAR(255) NOT NULL,
  ESTADO VARCHAR(255) NOT NULL,
  PERIODO VARCHAR(255) NOT NULL,
  /*NRO_ INT NOT NULL,*/
  PRIMARY KEY (id)
);

CREATE TABLE ACTIVOS (
  ID SERIAL,
  NOMBRE VARCHAR(255) NOT NULL,
  ETIQUETA VARCHAR(255) NOT NULL,
  EMPRESA VARCHAR(255) NOT NULL,
  RESPONSABLE VARCHAR(255) NOT NULL,
  EDIFICIO VARCHAR(255) NOT NULL,
  PISO VARCHAR(255) NOT NULL,
  TIPO_ACTIVO VARCHAR(255) NOT NULL,
  SUBTIPO_ACTIVO VARCHAR(255) NOT NULL,
  SUCURSAL VARCHAR(255) NOT NULL,
  NRO_CONTRATO  VARCHAR(255) NOT NULL,
  RUT VARCHAR(255) NOT NULL,
  FECHA_INICIO VARCHAR(255) NOT NULL,
  /*NRO_ INT NOT NULL,*/
  PRIMARY KEY (id)
);

CREATE TABLE REGISTRO_CONSUMO_ISF (
  ID SERIAL,
  PERIODO VARCHAR(255) NOT NULL,
  CENTRO_COSTO VARCHAR(255) NOT NULL,
  UNI_LOCATIVA VARCHAR(255) NOT NULL,
  EMPRESA VARCHAR(255) NOT NULL,
  TIPO_SERVICIO VARCHAR(255) NOT NULL,
  NRO_CONTRATO VARCHAR(255) NOT NULL,
  NRO_LECTURA VARCHAR(255) NOT NULL,
  NRO_CLIENTE VARCHAR(255) NOT NULL,
  NRO_MEDIDOR VARCHAR(255) NOT NULL,
  FOTO VARCHAR(255) NOT NULL,

  MONTO  INT NOT NULL,
  /*NRO_ INT NOT NULL,*/
  PRIMARY KEY (id)
);

CREATE TABLE USUARIOS(
  USUARIO_ID uuid DEFAULT uuid_generate_v4(),
  NOMBRE VARCHAR(255) NOT NULL,
  CORREO VARCHAR(255) NOT NULL UNIQUE,
  CONTRASENA VARCHAR(255) NOT NULL,
    ROL VARCHAR(255) ,
    ESTADO VARCHAR(255)  ,
    FECHA_CREACION DATE,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOTO VARCHAR(255)  ,
  PRIMARY KEY(USUARIO_ID)
);

CREATE TABLE TODO(
  TODO_ID SERIAL,
  USUARIO_ID UUID ,
  description VARCHAR(255),
  PRIMARY KEY (TODO_ID),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(USUARIO_ID)
);


INSERT INTO USUARIOS (NOMBRE, CORREO, CONTRASENA) VALUES ('henry', 'henryly213@gmail.com', 'kthl8822');